spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

token:
  access-key: thisistoolargeaccesstokenkeyfordummykeydataforlocalthisistoolargeaccesstokenkeyfordummykeydataforlocalthisistoolargeaccesstokenkeyfordummykeydataforlocalthisistoolargeaccesstokenkeyfordummykeydataforlocalthisistoolargeaccesstokenkeyfordummykeydataforlocalthisistoolargeaccesstokenkeyfordummykeydataforlocal
  refresh-key: thisistoolargerefreshtokenkeyfordummykeydataforlocalthisistoolargerefreshtokenkeyfordummykeydataforlocalthisistoolargerefreshtokenkeyfordummykeydataforlocalthisistoolargerefreshtokenkeyfordummykeydataforlocalthisistoolargerefreshtokenkeyfordummykeydataforlocalthisistoolargerefreshtokenkeyfordummykeydataforlocal
  issuer: localissuer
  access-expired-seconds: 3600
  refresh-expired-seconds: 259200
  access-expired-millis-seconds: 3600000
  refresh-expired-millis-seconds: 259200000
